print("Enter two numbers:")
a = input()
b = input()
sum = int(a) + int(b)
print("The Sum is:", sum)
difference = int(b) - int(a)
print("The Difference is:", difference)
product = int(a) * int(b)
print("The Product is:", product)
quotient = int(b) / int(a)
print("The Quotient is:", quotient)
