a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

print("\nResults:")
print(f"{a} == {b} →", a == b)
print(f"{a} != {b} →", a != b)
print(f"{a} > {b}  →", a > b)
print(f"{a} < {b}  →", a < b)
print(f"{a} >= {b} →", a >= b)
print(f"{a} <= {b} →", a <= b)