a=input("Enter first number : ")
b=input("Enter second number : ")
print("Results of Arithmetic Operations:")
print("Addition(+) = ", float(a)+float(b))
print("Subtraction(-) = ", float(a)-float(b))
print("Multiplication(*) = ", float(a)*float(b))
print("Division(/) = ", float(a)/float(b))
print("Modulus(%) = ", float(a)%float(b))
print("Exponentiation(**) = ", float(a)**float(b))
print("Floor Division(//) = ", float(a)//float(b))